stages:
  # - staging
  - production

# staging:
#     type: deploy
#     stage: staging
#     script:
#         - dpl --provider=heroku --app=$ARXIVTAG_STAGING --api-key=$HEROKU_API_KEY
#     only:
#         - staging

production:
    type: deploy
    stage: production
    before_script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
    script:
        - dpl --provider=heroku --app=$ARXIVTAG_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - master