name: App CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: tester
          POSTGRES_DB: arxiv_test
        ports: ['5432:5432']
        
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          
    - name: Run Tests
      run: |
        pytest --cov=app --junitxml=report.xml test/
