name: App CI

on: [push]

jobs:
  build:

    runs-on: python:3.9.9-slim-buster
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: tester
          POSTGRES_DB: arxiv_test
        ports: ['5432:5432']
        
    steps:
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          
    - name: Run Tests
      run: |
        pytest --cov=app --junitxml=report.xml test/
