name: App CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: tester
          POSTGRES_DB: arxiv_test
          POSTGRES_HOST_AUTH_METHOD: trust
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
    - uses: actions/checkout@master
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver wget
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        mv .env_example .env
    - name : Log cutaway
      run: |
        sed -i '/log_cli_level = 10/d' test/pytest.ini
        sed -i '/log_cli = true/d' test/pytest.ini
    - name: Run Tests
      env:
        DATABASE_URL: postgresql://runner:tester@localhost:5432/arxiv_test
        DATABASE_URL_TEST: postgresql://runner:tester@localhost:5432/arxiv_test
      run: |
        pytest --cov=app --junitxml=report.xml test/
